---
title: "階層ベイズと状態空間モデルで広告効果を推定したい"
authour: Y.Nakahashi
date: 2018-01-26
output: html_notebook
---

## 背景
これまでの記事で*Marketing Mix Modeling*におけるAdStock効果の推定について色々と書いてきましたが、その他にも試したいと思っているモデルがいくつかあります。その一つが階層ベイズモデルと状態空間モデルを同時に取り扱うものです。

例えば「地域別の売上推移のデータ」が手元にあると考えてみましょう。地域ではなく人や商品でも構いませんが、ある要因の各水準がそれぞれ時系列データを持っている状況（いわゆるパネルデータ）で、ひとまずここでは地域とします。このようなデータはあらゆる会社で保有していることでしょう。
今、各地域について*MMM*により広告効果を推定することを考えたとき、どのようなモデリングが可能でしょうか？

シンプルに考えれば、地域ごとに一つずつモデルを作るという方法が挙げられます。例えば地域の数が2つ3つしかなかったり、モデルの作成に時間をかけることが可能であればこの方法は有効かもしれません。しかし問題もあります。地域ごとに独立してモデルを作成するということは、**各地域のパラメータは互いに独立である**との仮定を置くことになるのですが、それは事実でしょうか？

例えば日本ではTVも新聞も全国で同じコンテンツが提供される割合が大きいでしょうし、購買行動に地域による差がそれほど認められるとは経験的にも思えません。もし仮に地域による異質性というものがそれほど強くないのであれば、むしろそういった情報を積極的に活かした方が良いのではないでしょうか？

そのような時に、パラメータ間に緩やかな縛りをかける方法として**階層ベイズモデル**という手法があります。詳しくは書籍を参考にして頂くとして、ここでは「各地域の広告効果を表すパラメータ$\beta$を生成する分布を仮定する」方法と説明しておきます。この分布の幅（バラつき、分散）が十分に大きければ広告効果は地域によって様々な値を取り得ますし、逆に分布の幅が極端に狭ければ地域ごとの広告効果に差はないことを意味します。


## 目的
この階層構造を持つモデルを、時系列データの分析でお馴染みの**状態空間モデル**と合わせて取り扱いたいというのが今回の試みです。具体的には、以下のようなモデルを想定しています。

$$
\begin{equation*}
y_{A,t} = \mu_{A,t} + \beta_{A}X_{A,t} + \epsilon_{A,t} \\
\mu_{A,t} \sim N(\mu_{A,t-1}, \sigma^{2}_{\mu}) \\
\epsilon_{A,t} \sim N(0, \sigma^{2}_{\epsilon}) \\
\beta_{A} \sim N(\beta_0, \sigma^{2}_{\beta})
\end{equation*}
$$

添字の`A`および`t`はそれぞれ地域（Area）と時点（time）を意味しており、$y_{A,t}$は「ある地域のt時点における観測値」となります。広告効果$\beta$に対して、その数値の元となる分布（ここでは正規分布）を仮定しています。

