---
title: "Rによるマーケティングミックスモデル"
author: ynakahashi
Date : 2017/5/23
output: html_notebook
---
### はじめに
このドキュメントは、Rを用いたマーケティングミックスモデル（*Marketing Mix Model*, MMM）の構築方法を、スクリプトを示しながら紹介することを目的として作成された。
想定している読者は、

- 広告効果の推定に関心があり、実データを用いて分析を行う機会を持つ
- MMMから得られた結果に何らかの洞察を加え、意思決定に活かすことが求められる
- （学術的見地というよりも）実ビジネスにおけるデータ分析の活用を目的とする

そして

- Rについての最低限の知識・経験を有する

であり、企業における意思決定部門に在籍している人や、統計を活用したコンサルタントを志す人物を念頭に置いている。


### Marketing Mix Model（MMM）の作り方
MMMの構築を始める前に考慮すべき点がいくつかある。
以下はその例である。

1. 分析の目的と考慮すべき要因
    - カバー範囲  
   MMMは目的変数に対する影響要因の特定およびその定量化を行うことで将来予測や広告投資の最適化に用いられる。目的変数および説明変数が決まっており、その関係の方向性が明らかである場合に有効な手法である。一方でアトリビューション分析のように説明要因間で複雑な関係性が生じている場合、その関連性を解き明かすような分析には向いていない。  
   またMMMは統計モデルを構築して評価するものが一般的である。マスメディアへの投資効果を評価するためには効果的であるが、デジタル広告の効果を見るのであれば単純なABテストで十分であるかもしれない。  
   **分析結果の活用を考えた時、MMMの構築はベストな方法であると言えるだろうか？**
     - ハロー効果、シナジー、カニバリ
    MMMは単一の目的変数を取り上げることが一般的である。目的変数が複数存在する状況において、目的変数同士が互いに関連し合う状況を説明する場合にはそのような仮定を表現する必要がある。  
    **目的変数同士の関連性の存在は明らかだろうか？** 

1. 商材
    - ライフサイクル  
   特に小売業において重要となるのが対象となる商材のライフサイクルである。一般にMMMの構築に当たっては売上の推移が安定している必要があり、新商品の発売直後または終売期など、通常と異なる推移を示す時期は分析に向いていない。特に終売に関して言えば、これはモデルで将来予測を行うというよりもオペレーションによって計画的に売りを行うものであるためMMMの対象とならないだろう。  
   **分析対象はプロダクトライフサイクルのどのステージだろうか？**

1. モデルの活用者
    - 活用する主体によってモデルのスコープや施策（変数）の粒度が変わる  
    **分析結果を活用することが想定されるのはどんな人物か？またMMMの結果はその担当者による意思決定に資する情報を与えるだろうか？**

上記は一部の例を示したものであり、その他にもMMMの構築が必須ではない状況があるだろう。逆に上記の状況であったとしてもMMMがビジネスに貢献することが期待できる場面もある。いずれにせよ、データを集めて分析を行うために必要なコストおよび分析によるリターンを事前に十分に検討しておくことは分析者の責任である。


#### データを集める
- 構造を整理し、集めるデータを特定する
    - カスタマージャーニー、顧客ファネルと照合する
    - 因果関係の仮説整理
- データを確認する
    - 抜け漏れのチェック
       - ３Cによるチェック
       - 媒体の種類によるチェック
    - 数値のチェック
       - 基本的には「露出量」を表すデータを取得する
             - TVならGRP
             - DigitalならPV、クリック数など
             - 新聞、雑誌、チラシなら部数
    - 実用性のチェック
       - 実績値であるか
          - 実績値ではない場合、その修正の必要性や方法
       - データの発生タイミング
          - 広告の場合、買い付け時なのか出稿した時なのか
          - 目的変数も購買なのか予約なのか、そのラグはどの程度か
       - 分析の目的が将来予測である場合、予測時に使用可能で無理のないラグを考慮しているか
       - 意思決定者やモデルの活用者に合わせた粒度への分解または統合
    - チェックリストの作成
       - ファイル名
       - 担当部署
       - 対象となるデータ

#### データを（一次）加工する
- 粒度は最小のものに合わせる
- 週次データの場合
    - 月曜始まりか日曜始まりなのか
    - 53週ある年の処理

#### データを眺める
- 時系列プロット
    - 時系列における注意点（単位根や共和分など）
- コレログラム

#### データを分析する
- 時系列を分解する
    - 移動平均による方法
    - 局所回帰による方法
- モデル化する方法
    - 加法型と積乗型
       - それぞれの考え方とプロコン
       - 積乗型における回帰係数は弾力性
    - アルゴリズム
       - 回帰、状態空間、エージェントベース

#### モデルを構築する
 - 季節性を取り上げる
     - 年次フラグ
     - 月次フラグ
     - 週次フラグ
     - 季節的なイベント
         - 暦（正月、年度、GW、お盆、SW、暮）
         - 気候、天候（春夏秋冬、気温、湿度、風速）

     - 突発的なイベント
         - 地震、台風、紛争、アメリカ大統領選挙、

 - 景況を表す
     - 景況指標
         - 種類
             - 先行、一致、遅行指数
             - CI、DIのようなインデックス
             
         - 目的変数にあった指標
                 - 車：自動車消費支出
                 - 家具：新築戸建数
                 - 家：住宅ローンの固定利率のような

     - 税制度の変更
         - 消費増税、グリーン税制（エコカー減税、エコポイント）など

 - 施策を取り込む
     - 施策の種類
         - プロモーションやキャンペーン
             - ラグ
             - 残存効果（Ad-Stock）
                 - Koyck型
                 - Almon型
                 - パルダモデル
                     - https://business-1.net/roi/
                     - http://www.mm-lab.jp/report/advertising-effectiveness-measurement-50-years-ago/

             - 飽和曲線
                 - Linear、Log、Sigmoid
             - 交互作用
             - 長期的効果と短期的効果

         - インセンティブ
             - 効果の定義（支出額をそのまま使えないので単価や利率を用いる）

     - 施策の投入
         - 全ての施策が＋となる

 - その他の要因を考慮する
     - パッケージの変更などの商品ライフサイクル
     - 耐久消費財の場合、発売からの経過期間（エイジング）

 - 変数を絞り込む
     - 優先順位
         - Ad-Stockから
     - 基準
         - 振り返りモデルと予測モデル

#### モデルを評価する
- 施策による貢献度を見積もる
    - 施策による効果の量
    - ベースラインの比率
    - ROI
       - 季節性を除外する
    - １００万円あたり獲得量
- 統計的な指標を算出する
    - AICなどのモデルの適合度
    - VIFなどの変数の妥当性
    - DWによる自己回帰の有無

#### モデルを活用する
- シミュレーション
- 最適化

#### モデルを高度化する
- 非線形な効果を推定する
    - 残存やエイジングなどを同時に推定
- 階層化
    - （エリアなど）階層化の対象となる要因をまとめる
       - 固定効果と変量効果
- 因果関係をモデルから特定する
    - SEMやベイジアンネットワークなどによる構造化
    - グレンジャー因果

